---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-django-migrate-service
  namespace: keptn
  labels:
    name: keptn-django-migrate-service
---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: keptn-django-migrate-service
  labels:
    name: keptn-django-migrate-service
rules:
- apiGroups: ["","apps"]
  resources: ["deployments","deployments/exec","deployments/logs","pods", "pods/exec"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: keptn-django-migrate-service
  labels:
    name: keptn-django-migrate-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-django-migrate-service
subjects:
- kind: ServiceAccount
  name: keptn-django-migrate-service
  namespace: keptn
---
# Deployment of our keptn-django-migrate-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptn-django-migrate-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: keptn-django-migrate-service
  replicas: 1
  template:
    metadata:
      labels:
        run: keptn-django-migrate-service
        app.kubernetes.io/name: keptn-django-migrate-service
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - name: keptn-django-migrate-service
          image: keptnsandbox/keptn-django-migrate-service:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.8.4
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.migrate.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: VERSION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName

      serviceAccountName: keptn-django-migrate-service
---
# Expose keptn-django-migrate-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: keptn-django-migrate-service
  namespace: keptn
  labels:
    run: keptn-django-migrate-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: keptn-django-migrate-service

